version: "1.0"

services:
  app:
    build: ./flaskapp
    links:
      - db
    networks:
      default:
        aliases:
          - "flask"
    ports:
      - "5000:5000"

  db:
    build: ./mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=flask
      - MYSQL_HOST=mysql
    networks:
      default:
        aliases:
        - "mysql"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro