version: "1.0"

services:
  app:
    build: ./flaskapp
    container_name: flask
    links:
      - db
    networks:
      default:
        aliases:
          - "flask"
    ports:
      - "5000:5000"

  db:
    build: ./mysql
    container_name: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
      - MYSQL_HOST=mysql
    networks:
      default:
        aliases:
          - "mysql"
    volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro